name: Check Run Workflow.

on:
  check_run:
    types: [created, rerequested, completed]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Check run event triggered!"
