name: 'Call Docker Action Workflow'

on:
  workflow_dispatch

jobs:
  run-docker-action:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Use the custom Docker action
      - name: Run Docker Action
        uses: ./docker-action  # Use the local path or a full GitHub repo path (e.g., your-username/your-repo@main)
        with:
          example_input: 'GitHub Actions'
