name: 'Call Composite Action Workflow'

on:
  push:
    branches:
      - main

jobs:
  use-composite-action:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Use the custom composite action
      - name: Run composite action
        uses: ./composite-action  # Relative path to the action
        with:
          greeting: 'GitHub Actions'  # Input passed to the composite action
