name: Repository Dispatch Workflow

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Repository dispatch event triggered!"
