name: Workflow Commands Example.

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create annotation for build error
      run: echo "::error file=app.js,line=1::Missing semicolon"
    - name: setup debug message.
      run: echo "::debug::Set the Octocat variable"
    - name: create annotation for notice
      run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
    - name: create annotation for warning
      run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
    - name: Group of log lines
      run: |
          echo "::group::My title"
          echo "Inside group"
          echo "second command"
          echo "third command" 
          echo "::endgroup::"



